export const GET_RECEPCIONISTAS = "GET_RECEPCIONISTAS";
export const GET_RECEPCIONISTAS_SUCCESS = "GET_RECEPCIONISTAS_SUCCESS";
export const GET_RECEPCIONISTAS_ERROR = "GET_RECEPCIONISTAS_ERROR";

export const ADD_RECEPCIONISTA = "ADD_RECEPCIONISTA";
export const ADD_RECEPCIONISTAS_SUCCESS = "ADD_RECEPCIONISTAS_SUCCESS";
export const ADD_RECEPCIONISTAS_ERROR = "ADD_RECEPCIONISTAS_ERROR";

export const DELETE_RECEPCIONISTA = "DELETE_RECEPCIONISTA";
export const DELETE_RECEPCIONISTAS_SUCCESS = "DELETE_RECEPCIONISTAS_SUCCESS";
export const DELETE_RECEPCIONISTAS_ERROR = "DELETE_RECEPCIONISTAS_ERROR";

export const EDIT_RECEPCIONISTAS = "EDIT_RECEPCIONISTAS";
export const EDIT_RECEPCIONISTAS_SUCCESS = "EDIT_RECEPCIONISTAS_SUCCESS";
export const EDIT_RECEPCIONISTAS_ERROR = "EDIT_RECEPCIONISTAS_ERROR";

export const SET_RECEPCIONISTAS='SET_RECEPCIONISTAS'
